/**
 * Created by OS on 8/30/2017.
 */
public class Problem2 {

//    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
//            1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

    public static int solve(int n) {
        int f0 = 1, f1 = 1, result = 0;
        while (f1 < n) {
            if (f1 % 2 == 0) result += f1;
            int tmp = f0;
            f0 = f1;
            f1 = f1 + tmp;
        }
        return result;
    }

}
